### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by nguyenvantruong1905** [khiemnguyen240900/vnese-id-extractor#1]
Chào bạn. mình cảm thấy dự án của bạn rất thú vị.
Bạn có thể cho mình xin dataset train yolov4 của bạn không.
cảm ơn bạn nhiều ^^

**Comment by khiemnguyen240900** [comment]
Chào bạn,

Nhóm mình sử dụng dataset gồm những thẻ CMND, CCCD và GPLX thật nên không thể chia sẻ cho bạn được.
Bạn có thể xin những data này từ những người thân, người xung quanh hoặc những data trên mạng nhé. Sau đó bạn dùng Data Augmentation để làm giàu data. Vì nhận diện này cũng khá đơn giản nên bạn có thể dùng ít data cũng được nhé. Nhóm mình train <1000 ảnh á.

**Comment by nguyenvantruong1905** [comment]
cảm ơn bạn nhé. mình sẽ làm vậy

**Comment by nguyenvantruong1905** [comment]
@khiemnguyen240900  cậu ơi, cho tớ hỏi, ở phần text detection cậu dùng model gì để detec vậy ạ. cậu có thể cho tớ keyword hoặc link không, cảm ơn cậu
